"""Init

Revision ID: e781f584b354
Revises: 
Create Date: 2024-11-02 08:33:54.582656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e781f584b354'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scooter',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('longitude', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('charge', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scooter')
    # ### end Alembic commands ###
